[package]
edition = "2018"
name = "nds"
version = "0.1.0"
authors = ["Maid Dog <maiddogsrl@gmail.com>"]
description = "Library for handling Nintendo DS ROM files."
documentation = "https://docs.rs/nds"
repository = "https://github.com/Roughsketch/nds"
readme = "README.md"
keywords = ["utility", "nds", "rom", "extract", "build"]
categories = ["filesystem"]
license = "MIT"
exclude = ["tests/*", "benches/*"]

[workspace]
members = [
    "narc",
    "nitro_fs",
]

[dependencies]
byteorder = "1.3"
failure = "0.1"
lazy_static = "1.2"
memmap = "0.7"
rayon = "1.0"

[dependencies.num]
version = "0.2"
default-features = false

[dependencies.nitro_fs]
path = "nitro_fs"

[dev-dependencies]
criterion = "0.2"
md5 = "0.6"

[[bench]]
name = "extract"
harness = false

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1